### ISSUE TITLE
Giraffe 5 ?

### ISSUE THREAD

**Issue by kaashyapan** [plotly/Dash.NET#12]
Latest version of Giraffe. (v5) has breaking changes. \
It supports minimum .net 5.

Most libraries in the dotnet world are going in this direction. 

Do you want to consider dropping support for netstandard and going all in on .net 5 ?

**Comment by kMutagene** [comment]
I think we can safely move this library to net5.0 once Plotly.NET has moved to net5.0. There were issues in the past that prevented that (e.g. usage within a script together with netstandard libraries). I think i can at least try to support both in Plotly.NET for now, so we do not block the transition in this project.

**Comment by kMutagene** [comment]
We can now move forward to net5.0 and update the Plotly.NET dependency to `2.0.0-preview.2`.

**Comment by kaashyapan** [comment]
Merged #13.
