### ISSUE TITLE
Use the same serialization configs for all backend implementations

### ISSUE THREAD

**Issue by kMutagene** [plotly/Dash.NET#26]
Raising this issue now as #24 might be merged with the problem still existent.

Copying my comment from that PR:

I copied the code from the Dash.NET.Dev app into the suave script to check if callbacks are working. They do, but the dropdown component did not render. The problem lies here:

https://github.com/plotly/Dash.NET/blob/4c2559e29d6e3dc0c2ecaf0cd0859ba7c376a640/src/Dash.NET/DashComponents/ComponentBase.fs#L115-L122

While these properties are uppercase in that record type, the dash renderer expect the Json properties to be lowercase:

![image](https://user-images.githubusercontent.com/21338071/133917296-d750f2ad-9454-4c1b-ac52-18b1a60a17fb.png)

This problem does not appear when using giraffe (which per default is also using Newtonsoft.Json, that's why I'm confused now). It is fixable by adding JsonPropertyAttributes to the record types, but i think it should be investigated why the json configs are different 

Let's make sure to file an issue and use the exact same Json serializer options for both apps, or this will be a nightmare to maintain, especially if there might be more backend implementations in the future

**Comment by ademar** [comment]
This should be fixed now by 80ad82aeceffa48b04902bf12ee5b8702bb90f7b
